/**
 * CI/CD workflow emitter for the generated application.
 *
 * Writes `.github/workflows/app-ci.yml` into the generated app. The workflow
 * has everything needed to run the generated application via **Docker** and
 * **docker compose**:
 *   - builds the image (`docker compose build`)
 *   - runs it (`docker compose up -d`) and health-checks it
 *   - smoke-tests the API, dumps logs, tears down
 *   - on push, builds & pushes the image to GHCR (`docker` build-push)
 *
 * It pairs with the Dockerfile + docker-compose.yml emitted by the docker
 * generator, so it is written whenever `--docker` is used.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

export function generateCiWorkflow(outDir: string, appName: string, port = 3000): string[] {
  const dir = path.join(outDir, ".github", "workflows");
  mkdirSync(dir, { recursive: true });

  const yml = `# Generated by the ERDwithAI EML CLI.
# Builds and runs "${appName}" via Docker + docker compose, then (on push)
# publishes the image to GitHub Container Registry.
name: ${appName} CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-compose:
    name: Build & run via docker compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (docker compose build)
        run: docker compose build

      - name: Start app (docker compose up)
        run: docker compose up -d

      - name: Wait for health
        run: |
          for i in $(seq 1 30); do
            if curl -fsS http://localhost:${port}/health; then
              echo "" && echo "App is healthy"; exit 0
            fi
            echo "waiting for app... ($i)"; sleep 2
          done
          echo "App did not become healthy in time"; docker compose logs; exit 1

      - name: Smoke-test the API
        run: |
          echo "GET /api/_meta:"
          curl -fsS http://localhost:${port}/api/_meta | head -c 600
          echo ""

      - name: Dump container logs
        if: always()
        run: docker compose logs

      - name: Tear down
        if: always()
        run: docker compose down -v

  publish-image:
    name: Build & push image to GHCR
    runs-on: ubuntu-latest
    needs: docker-compose
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/\${{ github.repository }}:latest
            ghcr.io/\${{ github.repository }}:\${{ github.sha }}
`;

  const file = path.join(dir, "app-ci.yml");
  writeFileSync(file, yml);
  return [path.join(".github", "workflows", "app-ci.yml")];
}
