/**
 * Docker emitter. Writes a Dockerfile, .dockerignore, and docker-compose.yml
 * for the generated zero-dependency Node app.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

export function generateDocker(outDir: string, appName: string): string[] {
  const written: string[] = [];

  writeFileSync(
    path.join(outDir, "Dockerfile"),
    `# Generated by the ERDwithAI EML CLI.
FROM node:20-alpine
WORKDIR /app

# Zero runtime dependencies — copy the source and run.
COPY package.json ./
COPY src ./src
COPY eml.model.json ./

ENV PORT=3000
ENV DATA_FILE=/data/store.json
VOLUME /data
EXPOSE 3000

CMD ["node", "src/server.js"]
`
  );
  written.push("Dockerfile");

  writeFileSync(
    path.join(outDir, ".dockerignore"),
    ["node_modules", "data", "*.log", ".git", ".DS_Store", ""].join("\n")
  );
  written.push(".dockerignore");

  writeFileSync(
    path.join(outDir, "docker-compose.yml"),
    `# Generated by the ERDwithAI EML CLI.
services:
  ${appName}:
    build: .
    container_name: ${appName}
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DATA_FILE: "/data/store.json"
    volumes:
      - ${appName}-data:/data
    restart: unless-stopped

volumes:
  ${appName}-data:
`
  );
  written.push("docker-compose.yml");

  return written;
}
