/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReportsRouteImport } from './routes/api/reports'
import { Route as ApiQueriesRouteImport } from './routes/api/queries'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFiltersRouteImport } from './routes/api/filters'
import { Route as ApiDataSourcesRouteImport } from './routes/api/data-sources'
import { Route as ApiDashboardsRouteImport } from './routes/api/dashboards'
import { Route as ApiChartsRouteImport } from './routes/api/charts'
import { Route as AuthedSqlEditorRouteImport } from './routes/_authed/sql-editor'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedBullBoardRouteImport } from './routes/_authed/bull-board'
import { Route as AuthedReportsIndexRouteImport } from './routes/_authed/reports/index'
import { Route as ShareReportIdRouteImport } from './routes/share/report/$id'
import { Route as ShareDashboardIdRouteImport } from './routes/share/dashboard/$id'
import { Route as ShareChartIdRouteImport } from './routes/share/chart/$id'
import { Route as ApiSqlValidateRouteImport } from './routes/api/sql/validate'
import { Route as ApiSqlExecuteRouteImport } from './routes/api/sql/execute'
import { Route as ApiReportsIdRouteImport } from './routes/api/reports/$id'
import { Route as ApiDataSourcesIdRouteImport } from './routes/api/data-sources/$id'
import { Route as ApiDashboardsIdRouteImport } from './routes/api/dashboards/$id'
import { Route as ApiChartsIdRouteImport } from './routes/api/charts/$id'
import { Route as ApiAuthPermissionsRouteImport } from './routes/api/auth/permissions'
import { Route as ApiSqlSchemaDataSourceIdRouteImport } from './routes/api/sql/schema.$dataSourceId'
import { Route as ApiReportsIdFiltersRouteImport } from './routes/api/reports/$id/filters'
import { Route as ApiReportsIdExportRouteImport } from './routes/api/reports/$id/export'
import { Route as ApiDashboardsIdWidgetsRouteImport } from './routes/api/dashboards/$id/widgets'
import { Route as ApiChartsIdFiltersRouteImport } from './routes/api/charts/$id/filters'
import { Route as AuthedReportsIdEditorRouteImport } from './routes/_authed/reports/$id/editor'
import { Route as ApiReportsIdFiltersFilterLinkIdRouteImport } from './routes/api/reports/$id/filters/$filterLinkId'
import { Route as ApiDashboardsIdWidgetsWidgetIdRouteImport } from './routes/api/dashboards/$id/widgets/$widgetId'
import { Route as ApiChartsIdFiltersFilterLinkIdRouteImport } from './routes/api/charts/$id/filters/$filterLinkId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueriesRoute = ApiQueriesRouteImport.update({
  id: '/api/queries',
  path: '/api/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFiltersRoute = ApiFiltersRouteImport.update({
  id: '/api/filters',
  path: '/api/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataSourcesRoute = ApiDataSourcesRouteImport.update({
  id: '/api/data-sources',
  path: '/api/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardsRoute = ApiDashboardsRouteImport.update({
  id: '/api/dashboards',
  path: '/api/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChartsRoute = ApiChartsRouteImport.update({
  id: '/api/charts',
  path: '/api/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSqlEditorRoute = AuthedSqlEditorRouteImport.update({
  id: '/sql-editor',
  path: '/sql-editor',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBullBoardRoute = AuthedBullBoardRouteImport.update({
  id: '/bull-board',
  path: '/bull-board',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsIndexRoute = AuthedReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthedRoute,
} as any)
const ShareReportIdRoute = ShareReportIdRouteImport.update({
  id: '/share/report/$id',
  path: '/share/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDashboardIdRoute = ShareDashboardIdRouteImport.update({
  id: '/share/dashboard/$id',
  path: '/share/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareChartIdRoute = ShareChartIdRouteImport.update({
  id: '/share/chart/$id',
  path: '/share/chart/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSqlValidateRoute = ApiSqlValidateRouteImport.update({
  id: '/api/sql/validate',
  path: '/api/sql/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSqlExecuteRoute = ApiSqlExecuteRouteImport.update({
  id: '/api/sql/execute',
  path: '/api/sql/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdRoute = ApiReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiReportsRoute,
} as any)
const ApiDataSourcesIdRoute = ApiDataSourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDataSourcesRoute,
} as any)
const ApiDashboardsIdRoute = ApiDashboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDashboardsRoute,
} as any)
const ApiChartsIdRoute = ApiChartsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiChartsRoute,
} as any)
const ApiAuthPermissionsRoute = ApiAuthPermissionsRouteImport.update({
  id: '/api/auth/permissions',
  path: '/api/auth/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSqlSchemaDataSourceIdRoute =
  ApiSqlSchemaDataSourceIdRouteImport.update({
    id: '/api/sql/schema/$dataSourceId',
    path: '/api/sql/schema/$dataSourceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportsIdFiltersRoute = ApiReportsIdFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => ApiReportsIdRoute,
} as any)
const ApiReportsIdExportRoute = ApiReportsIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiReportsIdRoute,
} as any)
const ApiDashboardsIdWidgetsRoute = ApiDashboardsIdWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => ApiDashboardsIdRoute,
} as any)
const ApiChartsIdFiltersRoute = ApiChartsIdFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => ApiChartsIdRoute,
} as any)
const AuthedReportsIdEditorRoute = AuthedReportsIdEditorRouteImport.update({
  id: '/reports/$id/editor',
  path: '/reports/$id/editor',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiReportsIdFiltersFilterLinkIdRoute =
  ApiReportsIdFiltersFilterLinkIdRouteImport.update({
    id: '/$filterLinkId',
    path: '/$filterLinkId',
    getParentRoute: () => ApiReportsIdFiltersRoute,
  } as any)
const ApiDashboardsIdWidgetsWidgetIdRoute =
  ApiDashboardsIdWidgetsWidgetIdRouteImport.update({
    id: '/$widgetId',
    path: '/$widgetId',
    getParentRoute: () => ApiDashboardsIdWidgetsRoute,
  } as any)
const ApiChartsIdFiltersFilterLinkIdRoute =
  ApiChartsIdFiltersFilterLinkIdRouteImport.update({
    id: '/$filterLinkId',
    path: '/$filterLinkId',
    getParentRoute: () => ApiChartsIdFiltersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bull-board': typeof AuthedBullBoardRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/sql-editor': typeof AuthedSqlEditorRoute
  '/api/charts': typeof ApiChartsRouteWithChildren
  '/api/dashboards': typeof ApiDashboardsRouteWithChildren
  '/api/data-sources': typeof ApiDataSourcesRouteWithChildren
  '/api/filters': typeof ApiFiltersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/queries': typeof ApiQueriesRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/auth/permissions': typeof ApiAuthPermissionsRoute
  '/api/charts/$id': typeof ApiChartsIdRouteWithChildren
  '/api/dashboards/$id': typeof ApiDashboardsIdRouteWithChildren
  '/api/data-sources/$id': typeof ApiDataSourcesIdRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/sql/execute': typeof ApiSqlExecuteRoute
  '/api/sql/validate': typeof ApiSqlValidateRoute
  '/share/chart/$id': typeof ShareChartIdRoute
  '/share/dashboard/$id': typeof ShareDashboardIdRoute
  '/share/report/$id': typeof ShareReportIdRoute
  '/reports/': typeof AuthedReportsIndexRoute
  '/reports/$id/editor': typeof AuthedReportsIdEditorRoute
  '/api/charts/$id/filters': typeof ApiChartsIdFiltersRouteWithChildren
  '/api/dashboards/$id/widgets': typeof ApiDashboardsIdWidgetsRouteWithChildren
  '/api/reports/$id/export': typeof ApiReportsIdExportRoute
  '/api/reports/$id/filters': typeof ApiReportsIdFiltersRouteWithChildren
  '/api/sql/schema/$dataSourceId': typeof ApiSqlSchemaDataSourceIdRoute
  '/api/charts/$id/filters/$filterLinkId': typeof ApiChartsIdFiltersFilterLinkIdRoute
  '/api/dashboards/$id/widgets/$widgetId': typeof ApiDashboardsIdWidgetsWidgetIdRoute
  '/api/reports/$id/filters/$filterLinkId': typeof ApiReportsIdFiltersFilterLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bull-board': typeof AuthedBullBoardRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/sql-editor': typeof AuthedSqlEditorRoute
  '/api/charts': typeof ApiChartsRouteWithChildren
  '/api/dashboards': typeof ApiDashboardsRouteWithChildren
  '/api/data-sources': typeof ApiDataSourcesRouteWithChildren
  '/api/filters': typeof ApiFiltersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/queries': typeof ApiQueriesRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/auth/permissions': typeof ApiAuthPermissionsRoute
  '/api/charts/$id': typeof ApiChartsIdRouteWithChildren
  '/api/dashboards/$id': typeof ApiDashboardsIdRouteWithChildren
  '/api/data-sources/$id': typeof ApiDataSourcesIdRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/sql/execute': typeof ApiSqlExecuteRoute
  '/api/sql/validate': typeof ApiSqlValidateRoute
  '/share/chart/$id': typeof ShareChartIdRoute
  '/share/dashboard/$id': typeof ShareDashboardIdRoute
  '/share/report/$id': typeof ShareReportIdRoute
  '/reports': typeof AuthedReportsIndexRoute
  '/reports/$id/editor': typeof AuthedReportsIdEditorRoute
  '/api/charts/$id/filters': typeof ApiChartsIdFiltersRouteWithChildren
  '/api/dashboards/$id/widgets': typeof ApiDashboardsIdWidgetsRouteWithChildren
  '/api/reports/$id/export': typeof ApiReportsIdExportRoute
  '/api/reports/$id/filters': typeof ApiReportsIdFiltersRouteWithChildren
  '/api/sql/schema/$dataSourceId': typeof ApiSqlSchemaDataSourceIdRoute
  '/api/charts/$id/filters/$filterLinkId': typeof ApiChartsIdFiltersFilterLinkIdRoute
  '/api/dashboards/$id/widgets/$widgetId': typeof ApiDashboardsIdWidgetsWidgetIdRoute
  '/api/reports/$id/filters/$filterLinkId': typeof ApiReportsIdFiltersFilterLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/bull-board': typeof AuthedBullBoardRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/sql-editor': typeof AuthedSqlEditorRoute
  '/api/charts': typeof ApiChartsRouteWithChildren
  '/api/dashboards': typeof ApiDashboardsRouteWithChildren
  '/api/data-sources': typeof ApiDataSourcesRouteWithChildren
  '/api/filters': typeof ApiFiltersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/queries': typeof ApiQueriesRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/auth/permissions': typeof ApiAuthPermissionsRoute
  '/api/charts/$id': typeof ApiChartsIdRouteWithChildren
  '/api/dashboards/$id': typeof ApiDashboardsIdRouteWithChildren
  '/api/data-sources/$id': typeof ApiDataSourcesIdRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/sql/execute': typeof ApiSqlExecuteRoute
  '/api/sql/validate': typeof ApiSqlValidateRoute
  '/share/chart/$id': typeof ShareChartIdRoute
  '/share/dashboard/$id': typeof ShareDashboardIdRoute
  '/share/report/$id': typeof ShareReportIdRoute
  '/_authed/reports/': typeof AuthedReportsIndexRoute
  '/_authed/reports/$id/editor': typeof AuthedReportsIdEditorRoute
  '/api/charts/$id/filters': typeof ApiChartsIdFiltersRouteWithChildren
  '/api/dashboards/$id/widgets': typeof ApiDashboardsIdWidgetsRouteWithChildren
  '/api/reports/$id/export': typeof ApiReportsIdExportRoute
  '/api/reports/$id/filters': typeof ApiReportsIdFiltersRouteWithChildren
  '/api/sql/schema/$dataSourceId': typeof ApiSqlSchemaDataSourceIdRoute
  '/api/charts/$id/filters/$filterLinkId': typeof ApiChartsIdFiltersFilterLinkIdRoute
  '/api/dashboards/$id/widgets/$widgetId': typeof ApiDashboardsIdWidgetsWidgetIdRoute
  '/api/reports/$id/filters/$filterLinkId': typeof ApiReportsIdFiltersFilterLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bull-board'
    | '/dashboard'
    | '/sql-editor'
    | '/api/charts'
    | '/api/dashboards'
    | '/api/data-sources'
    | '/api/filters'
    | '/api/health'
    | '/api/jobs'
    | '/api/queries'
    | '/api/reports'
    | '/api/auth/permissions'
    | '/api/charts/$id'
    | '/api/dashboards/$id'
    | '/api/data-sources/$id'
    | '/api/reports/$id'
    | '/api/sql/execute'
    | '/api/sql/validate'
    | '/share/chart/$id'
    | '/share/dashboard/$id'
    | '/share/report/$id'
    | '/reports/'
    | '/reports/$id/editor'
    | '/api/charts/$id/filters'
    | '/api/dashboards/$id/widgets'
    | '/api/reports/$id/export'
    | '/api/reports/$id/filters'
    | '/api/sql/schema/$dataSourceId'
    | '/api/charts/$id/filters/$filterLinkId'
    | '/api/dashboards/$id/widgets/$widgetId'
    | '/api/reports/$id/filters/$filterLinkId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bull-board'
    | '/dashboard'
    | '/sql-editor'
    | '/api/charts'
    | '/api/dashboards'
    | '/api/data-sources'
    | '/api/filters'
    | '/api/health'
    | '/api/jobs'
    | '/api/queries'
    | '/api/reports'
    | '/api/auth/permissions'
    | '/api/charts/$id'
    | '/api/dashboards/$id'
    | '/api/data-sources/$id'
    | '/api/reports/$id'
    | '/api/sql/execute'
    | '/api/sql/validate'
    | '/share/chart/$id'
    | '/share/dashboard/$id'
    | '/share/report/$id'
    | '/reports'
    | '/reports/$id/editor'
    | '/api/charts/$id/filters'
    | '/api/dashboards/$id/widgets'
    | '/api/reports/$id/export'
    | '/api/reports/$id/filters'
    | '/api/sql/schema/$dataSourceId'
    | '/api/charts/$id/filters/$filterLinkId'
    | '/api/dashboards/$id/widgets/$widgetId'
    | '/api/reports/$id/filters/$filterLinkId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/bull-board'
    | '/_authed/dashboard'
    | '/_authed/sql-editor'
    | '/api/charts'
    | '/api/dashboards'
    | '/api/data-sources'
    | '/api/filters'
    | '/api/health'
    | '/api/jobs'
    | '/api/queries'
    | '/api/reports'
    | '/api/auth/permissions'
    | '/api/charts/$id'
    | '/api/dashboards/$id'
    | '/api/data-sources/$id'
    | '/api/reports/$id'
    | '/api/sql/execute'
    | '/api/sql/validate'
    | '/share/chart/$id'
    | '/share/dashboard/$id'
    | '/share/report/$id'
    | '/_authed/reports/'
    | '/_authed/reports/$id/editor'
    | '/api/charts/$id/filters'
    | '/api/dashboards/$id/widgets'
    | '/api/reports/$id/export'
    | '/api/reports/$id/filters'
    | '/api/sql/schema/$dataSourceId'
    | '/api/charts/$id/filters/$filterLinkId'
    | '/api/dashboards/$id/widgets/$widgetId'
    | '/api/reports/$id/filters/$filterLinkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChartsRoute: typeof ApiChartsRouteWithChildren
  ApiDashboardsRoute: typeof ApiDashboardsRouteWithChildren
  ApiDataSourcesRoute: typeof ApiDataSourcesRouteWithChildren
  ApiFiltersRoute: typeof ApiFiltersRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiQueriesRoute: typeof ApiQueriesRoute
  ApiReportsRoute: typeof ApiReportsRouteWithChildren
  ApiAuthPermissionsRoute: typeof ApiAuthPermissionsRoute
  ApiSqlExecuteRoute: typeof ApiSqlExecuteRoute
  ApiSqlValidateRoute: typeof ApiSqlValidateRoute
  ShareChartIdRoute: typeof ShareChartIdRoute
  ShareDashboardIdRoute: typeof ShareDashboardIdRoute
  ShareReportIdRoute: typeof ShareReportIdRoute
  ApiSqlSchemaDataSourceIdRoute: typeof ApiSqlSchemaDataSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queries': {
      id: '/api/queries'
      path: '/api/queries'
      fullPath: '/api/queries'
      preLoaderRoute: typeof ApiQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/filters': {
      id: '/api/filters'
      path: '/api/filters'
      fullPath: '/api/filters'
      preLoaderRoute: typeof ApiFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-sources': {
      id: '/api/data-sources'
      path: '/api/data-sources'
      fullPath: '/api/data-sources'
      preLoaderRoute: typeof ApiDataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboards': {
      id: '/api/dashboards'
      path: '/api/dashboards'
      fullPath: '/api/dashboards'
      preLoaderRoute: typeof ApiDashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/charts': {
      id: '/api/charts'
      path: '/api/charts'
      fullPath: '/api/charts'
      preLoaderRoute: typeof ApiChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/sql-editor': {
      id: '/_authed/sql-editor'
      path: '/sql-editor'
      fullPath: '/sql-editor'
      preLoaderRoute: typeof AuthedSqlEditorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bull-board': {
      id: '/_authed/bull-board'
      path: '/bull-board'
      fullPath: '/bull-board'
      preLoaderRoute: typeof AuthedBullBoardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports/': {
      id: '/_authed/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthedReportsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/share/report/$id': {
      id: '/share/report/$id'
      path: '/share/report/$id'
      fullPath: '/share/report/$id'
      preLoaderRoute: typeof ShareReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/dashboard/$id': {
      id: '/share/dashboard/$id'
      path: '/share/dashboard/$id'
      fullPath: '/share/dashboard/$id'
      preLoaderRoute: typeof ShareDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/chart/$id': {
      id: '/share/chart/$id'
      path: '/share/chart/$id'
      fullPath: '/share/chart/$id'
      preLoaderRoute: typeof ShareChartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sql/validate': {
      id: '/api/sql/validate'
      path: '/api/sql/validate'
      fullPath: '/api/sql/validate'
      preLoaderRoute: typeof ApiSqlValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sql/execute': {
      id: '/api/sql/execute'
      path: '/api/sql/execute'
      fullPath: '/api/sql/execute'
      preLoaderRoute: typeof ApiSqlExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id': {
      id: '/api/reports/$id'
      path: '/$id'
      fullPath: '/api/reports/$id'
      preLoaderRoute: typeof ApiReportsIdRouteImport
      parentRoute: typeof ApiReportsRoute
    }
    '/api/data-sources/$id': {
      id: '/api/data-sources/$id'
      path: '/$id'
      fullPath: '/api/data-sources/$id'
      preLoaderRoute: typeof ApiDataSourcesIdRouteImport
      parentRoute: typeof ApiDataSourcesRoute
    }
    '/api/dashboards/$id': {
      id: '/api/dashboards/$id'
      path: '/$id'
      fullPath: '/api/dashboards/$id'
      preLoaderRoute: typeof ApiDashboardsIdRouteImport
      parentRoute: typeof ApiDashboardsRoute
    }
    '/api/charts/$id': {
      id: '/api/charts/$id'
      path: '/$id'
      fullPath: '/api/charts/$id'
      preLoaderRoute: typeof ApiChartsIdRouteImport
      parentRoute: typeof ApiChartsRoute
    }
    '/api/auth/permissions': {
      id: '/api/auth/permissions'
      path: '/api/auth/permissions'
      fullPath: '/api/auth/permissions'
      preLoaderRoute: typeof ApiAuthPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sql/schema/$dataSourceId': {
      id: '/api/sql/schema/$dataSourceId'
      path: '/api/sql/schema/$dataSourceId'
      fullPath: '/api/sql/schema/$dataSourceId'
      preLoaderRoute: typeof ApiSqlSchemaDataSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id/filters': {
      id: '/api/reports/$id/filters'
      path: '/filters'
      fullPath: '/api/reports/$id/filters'
      preLoaderRoute: typeof ApiReportsIdFiltersRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
    '/api/reports/$id/export': {
      id: '/api/reports/$id/export'
      path: '/export'
      fullPath: '/api/reports/$id/export'
      preLoaderRoute: typeof ApiReportsIdExportRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
    '/api/dashboards/$id/widgets': {
      id: '/api/dashboards/$id/widgets'
      path: '/widgets'
      fullPath: '/api/dashboards/$id/widgets'
      preLoaderRoute: typeof ApiDashboardsIdWidgetsRouteImport
      parentRoute: typeof ApiDashboardsIdRoute
    }
    '/api/charts/$id/filters': {
      id: '/api/charts/$id/filters'
      path: '/filters'
      fullPath: '/api/charts/$id/filters'
      preLoaderRoute: typeof ApiChartsIdFiltersRouteImport
      parentRoute: typeof ApiChartsIdRoute
    }
    '/_authed/reports/$id/editor': {
      id: '/_authed/reports/$id/editor'
      path: '/reports/$id/editor'
      fullPath: '/reports/$id/editor'
      preLoaderRoute: typeof AuthedReportsIdEditorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/reports/$id/filters/$filterLinkId': {
      id: '/api/reports/$id/filters/$filterLinkId'
      path: '/$filterLinkId'
      fullPath: '/api/reports/$id/filters/$filterLinkId'
      preLoaderRoute: typeof ApiReportsIdFiltersFilterLinkIdRouteImport
      parentRoute: typeof ApiReportsIdFiltersRoute
    }
    '/api/dashboards/$id/widgets/$widgetId': {
      id: '/api/dashboards/$id/widgets/$widgetId'
      path: '/$widgetId'
      fullPath: '/api/dashboards/$id/widgets/$widgetId'
      preLoaderRoute: typeof ApiDashboardsIdWidgetsWidgetIdRouteImport
      parentRoute: typeof ApiDashboardsIdWidgetsRoute
    }
    '/api/charts/$id/filters/$filterLinkId': {
      id: '/api/charts/$id/filters/$filterLinkId'
      path: '/$filterLinkId'
      fullPath: '/api/charts/$id/filters/$filterLinkId'
      preLoaderRoute: typeof ApiChartsIdFiltersFilterLinkIdRouteImport
      parentRoute: typeof ApiChartsIdFiltersRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBullBoardRoute: typeof AuthedBullBoardRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSqlEditorRoute: typeof AuthedSqlEditorRoute
  AuthedReportsIndexRoute: typeof AuthedReportsIndexRoute
  AuthedReportsIdEditorRoute: typeof AuthedReportsIdEditorRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBullBoardRoute: AuthedBullBoardRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSqlEditorRoute: AuthedSqlEditorRoute,
  AuthedReportsIndexRoute: AuthedReportsIndexRoute,
  AuthedReportsIdEditorRoute: AuthedReportsIdEditorRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiChartsIdFiltersRouteChildren {
  ApiChartsIdFiltersFilterLinkIdRoute: typeof ApiChartsIdFiltersFilterLinkIdRoute
}

const ApiChartsIdFiltersRouteChildren: ApiChartsIdFiltersRouteChildren = {
  ApiChartsIdFiltersFilterLinkIdRoute: ApiChartsIdFiltersFilterLinkIdRoute,
}

const ApiChartsIdFiltersRouteWithChildren =
  ApiChartsIdFiltersRoute._addFileChildren(ApiChartsIdFiltersRouteChildren)

interface ApiChartsIdRouteChildren {
  ApiChartsIdFiltersRoute: typeof ApiChartsIdFiltersRouteWithChildren
}

const ApiChartsIdRouteChildren: ApiChartsIdRouteChildren = {
  ApiChartsIdFiltersRoute: ApiChartsIdFiltersRouteWithChildren,
}

const ApiChartsIdRouteWithChildren = ApiChartsIdRoute._addFileChildren(
  ApiChartsIdRouteChildren,
)

interface ApiChartsRouteChildren {
  ApiChartsIdRoute: typeof ApiChartsIdRouteWithChildren
}

const ApiChartsRouteChildren: ApiChartsRouteChildren = {
  ApiChartsIdRoute: ApiChartsIdRouteWithChildren,
}

const ApiChartsRouteWithChildren = ApiChartsRoute._addFileChildren(
  ApiChartsRouteChildren,
)

interface ApiDashboardsIdWidgetsRouteChildren {
  ApiDashboardsIdWidgetsWidgetIdRoute: typeof ApiDashboardsIdWidgetsWidgetIdRoute
}

const ApiDashboardsIdWidgetsRouteChildren: ApiDashboardsIdWidgetsRouteChildren =
  {
    ApiDashboardsIdWidgetsWidgetIdRoute: ApiDashboardsIdWidgetsWidgetIdRoute,
  }

const ApiDashboardsIdWidgetsRouteWithChildren =
  ApiDashboardsIdWidgetsRoute._addFileChildren(
    ApiDashboardsIdWidgetsRouteChildren,
  )

interface ApiDashboardsIdRouteChildren {
  ApiDashboardsIdWidgetsRoute: typeof ApiDashboardsIdWidgetsRouteWithChildren
}

const ApiDashboardsIdRouteChildren: ApiDashboardsIdRouteChildren = {
  ApiDashboardsIdWidgetsRoute: ApiDashboardsIdWidgetsRouteWithChildren,
}

const ApiDashboardsIdRouteWithChildren = ApiDashboardsIdRoute._addFileChildren(
  ApiDashboardsIdRouteChildren,
)

interface ApiDashboardsRouteChildren {
  ApiDashboardsIdRoute: typeof ApiDashboardsIdRouteWithChildren
}

const ApiDashboardsRouteChildren: ApiDashboardsRouteChildren = {
  ApiDashboardsIdRoute: ApiDashboardsIdRouteWithChildren,
}

const ApiDashboardsRouteWithChildren = ApiDashboardsRoute._addFileChildren(
  ApiDashboardsRouteChildren,
)

interface ApiDataSourcesRouteChildren {
  ApiDataSourcesIdRoute: typeof ApiDataSourcesIdRoute
}

const ApiDataSourcesRouteChildren: ApiDataSourcesRouteChildren = {
  ApiDataSourcesIdRoute: ApiDataSourcesIdRoute,
}

const ApiDataSourcesRouteWithChildren = ApiDataSourcesRoute._addFileChildren(
  ApiDataSourcesRouteChildren,
)

interface ApiReportsIdFiltersRouteChildren {
  ApiReportsIdFiltersFilterLinkIdRoute: typeof ApiReportsIdFiltersFilterLinkIdRoute
}

const ApiReportsIdFiltersRouteChildren: ApiReportsIdFiltersRouteChildren = {
  ApiReportsIdFiltersFilterLinkIdRoute: ApiReportsIdFiltersFilterLinkIdRoute,
}

const ApiReportsIdFiltersRouteWithChildren =
  ApiReportsIdFiltersRoute._addFileChildren(ApiReportsIdFiltersRouteChildren)

interface ApiReportsIdRouteChildren {
  ApiReportsIdExportRoute: typeof ApiReportsIdExportRoute
  ApiReportsIdFiltersRoute: typeof ApiReportsIdFiltersRouteWithChildren
}

const ApiReportsIdRouteChildren: ApiReportsIdRouteChildren = {
  ApiReportsIdExportRoute: ApiReportsIdExportRoute,
  ApiReportsIdFiltersRoute: ApiReportsIdFiltersRouteWithChildren,
}

const ApiReportsIdRouteWithChildren = ApiReportsIdRoute._addFileChildren(
  ApiReportsIdRouteChildren,
)

interface ApiReportsRouteChildren {
  ApiReportsIdRoute: typeof ApiReportsIdRouteWithChildren
}

const ApiReportsRouteChildren: ApiReportsRouteChildren = {
  ApiReportsIdRoute: ApiReportsIdRouteWithChildren,
}

const ApiReportsRouteWithChildren = ApiReportsRoute._addFileChildren(
  ApiReportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChartsRoute: ApiChartsRouteWithChildren,
  ApiDashboardsRoute: ApiDashboardsRouteWithChildren,
  ApiDataSourcesRoute: ApiDataSourcesRouteWithChildren,
  ApiFiltersRoute: ApiFiltersRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiQueriesRoute: ApiQueriesRoute,
  ApiReportsRoute: ApiReportsRouteWithChildren,
  ApiAuthPermissionsRoute: ApiAuthPermissionsRoute,
  ApiSqlExecuteRoute: ApiSqlExecuteRoute,
  ApiSqlValidateRoute: ApiSqlValidateRoute,
  ShareChartIdRoute: ShareChartIdRoute,
  ShareDashboardIdRoute: ShareDashboardIdRoute,
  ShareReportIdRoute: ShareReportIdRoute,
  ApiSqlSchemaDataSourceIdRoute: ApiSqlSchemaDataSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
